<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>txt</string>
    </array>
    <key>keyEquivalent</key>
    <string>^~T</string>
    <key>name</key>
    <string>TodoTXT</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>match</key>
        <string>^\([A-Z]\)</string>
        <key>name</key>
        <string>constant.language.todotxt.priority</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\@\S*</string>
        <key>name</key>
        <string>entity.name.tag.todotxt.context</string>
      </dict>      
      <dict>
        <key>match</key>
        <string>\+\S*</string>
        <key>name</key>
        <string>entity.name.tag.todotxt.project</string>
      </dict>      
      <dict>
        <key>match</key>
        <string>^x\s.*$</string>
        <key>name</key>
        <string>comment.line.todotxt</string>
      </dict>      
    </array>
    <key>scopeName</key>
    <string>text.todotxt</string>
    <key>uuid</key>
    <string>B68B5C70-7D5A-11E0-A411-0800200C9A66</string>
  </dict>
</plist>
