<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>txt</string>
    </array>
    <key>keyEquivalent</key>
    <string>^~T</string>
    <key>name</key>
    <string>TodoTXT</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>match</key>
        <string>^\(A\)</string>
        <key>name</key>
        <string>markup.bold.todotxt.priority.a</string>
      </dict>
      <dict>
        <key>match</key>
        <string>^\(B\)</string>
        <key>name</key>
        <string>markup.bold.todotxt.priority.b</string>
      </dict>
      <dict>
        <key>match</key>
        <string>^\(C\)</string>
        <key>name</key>
        <string>markup.bold.todotxt.priority.c</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\@\S*</string>
        <key>name</key>
        <string>markup.underline.todotxt.context</string>
      </dict>      
      <dict>
        <key>match</key>
        <string>\+\S*</string>
        <key>name</key>
        <string>markup.italic.todotxt.project</string>
      </dict>      
    </array>
    <key>scopeName</key>
    <string>text.todotxt</string>
    <key>uuid</key>
    <string>B68B5C70-7D5A-11E0-A411-0800200C9A66</string>
  </dict>
</plist>
